# Icon
favicon: /favicon.ico
# SEO
keywords: Hexo, Gruntjs, Nodejs, Reactjs, Vuejs
# Header
page_background: \background.jpg
page_menu_button: dark
post_background: \backgrounds.png
post_menu_button: light
title_plancehold: 随笔
author:
  rounded: true  # 圆形头像
  opacity: 0.8   # 透明度
  head: \head.jpg
  signature: For Ren Su Xi
navication:
  - name: Github
    link: https://github.com
  - name: weibo
    link: https://weibo.com/p/100808ffc196765d4a7a47f222db0a11953c8f/super_index
# content
content_width: 800
# Footer
## Social icon list: [facebook, twitter, weibo, wechat, github, stackoverflow, linkin, email, segmentfault, flickr, zhihu, disqus, douban, bilibili]
social:
  - name: Github
    icon: github
    link: https://github.com
  - name: Weibo
    icon: weibo
    link: https://weibo.com/u/7926092865
#Duoshuo
duoshuo:
  enable: false  # 关闭多说
# Copyright
copyright:
  record: false
  hexo: true
  laughing: true